openapi: 3.2.0
info:
  title: Amazon CodeBuild Builds API
  description: AWS CodeBuild is a fully managed continuous integration service that compiles source code, runs tests, and produces software packages that are ready to deploy. With CodeBuild, you don't need to provision, manage, and scale your own build servers. CodeBuild scales continuously and processes multiple builds concurrently.
  version: '2016-10-06'
  contact:
    name: Amazon Web Services
    url: https://aws.amazon.com/contact-us/
  termsOfService: https://aws.amazon.com/service-terms/
servers:
- url: https://codebuild.{region}.amazonaws.com
  description: Amazon CodeBuild Regional Endpoint
  variables:
    region:
      default: us-east-1
      description: AWS Region
tags:
- name: Builds
  description: Operations for starting, stopping, and viewing builds
paths:
  /builds/start:
    post:
      operationId: StartBuild
      summary: Amazon CodeBuild Start a Build
      description: Starts running a build with the settings defined in the project.
      tags:
      - Builds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartBuildRequest'
            examples:
              StartBuildRequestExample:
                summary: Default StartBuild request
                x-microcks-default: true
                value:
                  projectName: example-resource
                  sourceVersion: 1.0.0
                  environmentVariablesOverride:
                  - name: example-resource
                    value: example-value
                    type: STANDARD
      responses:
        '200':
          description: Build started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartBuildResponse'
              examples:
                StartBuild200Example:
                  summary: Default StartBuild 200 response
                  x-microcks-default: true
                  value:
                    build:
                      id: '500123'
                      arn: arn:aws:service:us-east-1:123456789012:resource/example
                      buildNumber: 1
                      startTime: example-value
                      endTime: example-value
                      currentPhase: example-value
                      buildStatus: SUCCEEDED
                      projectName: example-resource
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                StartBuild400Example:
                  summary: Default StartBuild 400 response
                  x-microcks-default: true
                  value:
                    message: example-value
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                StartBuild404Example:
                  summary: Default StartBuild 404 response
                  x-microcks-default: true
                  value:
                    message: example-value
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                StartBuild500Example:
                  summary: Default StartBuild 500 response
                  x-microcks-default: true
                  value:
                    message: example-value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /builds/stop:
    post:
      operationId: StopBuild
      summary: Amazon CodeBuild Stop a Build
      description: Attempts to stop running a build.
      tags:
      - Builds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - id
              properties:
                id:
                  type: string
                  description: The ID of the build to stop.
            examples:
              StopBuildRequestExample:
                summary: Default StopBuild request
                x-microcks-default: true
                value:
                  id: '500123'
      responses:
        '200':
          description: Build stopped
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopBuildResponse'
              examples:
                StopBuild200Example:
                  summary: Default StopBuild 200 response
                  x-microcks-default: true
                  value:
                    build:
                      id: '500123'
                      arn: arn:aws:service:us-east-1:123456789012:resource/example
                      buildNumber: 1
                      startTime: example-value
                      endTime: example-value
                      currentPhase: example-value
                      buildStatus: SUCCEEDED
                      projectName: example-resource
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                StopBuild400Example:
                  summary: Default StopBuild 400 response
                  x-microcks-default: true
                  value:
                    message: example-value
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                StopBuild404Example:
                  summary: Default StopBuild 404 response
                  x-microcks-default: true
                  value:
                    message: example-value
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                StopBuild500Example:
                  summary: Default StopBuild 500 response
                  x-microcks-default: true
                  value:
                    message: example-value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /builds:
    post:
      operationId: BatchGetBuilds
      summary: Amazon CodeBuild Get Build Details
      description: Gets information about one or more builds.
      tags:
      - Builds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - ids
              properties:
                ids:
                  type: array
                  items:
                    type: string
                  description: The IDs of the builds.
            examples:
              BatchGetBuildsRequestExample:
                summary: Default BatchGetBuilds request
                x-microcks-default: true
                value:
                  ids:
                  - '500123'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchGetBuildsResponse'
              examples:
                BatchGetBuilds200Example:
                  summary: Default BatchGetBuilds 200 response
                  x-microcks-default: true
                  value:
                    builds:
                    - id: '500123'
                      arn: arn:aws:service:us-east-1:123456789012:resource/example
                      buildNumber: 1
                      startTime: example-value
                      endTime: example-value
                      currentPhase: example-value
                      buildStatus: SUCCEEDED
                      projectName: example-resource
                    buildsNotFound:
                    - example-value
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                BatchGetBuilds400Example:
                  summary: Default BatchGetBuilds 400 response
                  x-microcks-default: true
                  value:
                    message: example-value
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                BatchGetBuilds500Example:
                  summary: Default BatchGetBuilds 500 response
                  x-microcks-default: true
                  value:
                    message: example-value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    StartBuildRequest:
      type: object
      required:
      - projectName
      properties:
        projectName:
          type: string
          description: The name of the CodeBuild build project.
        sourceVersion:
          type: string
          description: The version of the build input to be built.
        environmentVariablesOverride:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
              type:
                type: string
    StopBuildResponse:
      type: object
      properties:
        build:
          $ref: '#/components/schemas/Build'
    BatchGetBuildsResponse:
      type: object
      properties:
        builds:
          type: array
          items:
            $ref: '#/components/schemas/Build'
        buildsNotFound:
          type: array
          items:
            type: string
    StartBuildResponse:
      type: object
      properties:
        build:
          $ref: '#/components/schemas/Build'
    ResourceNotFoundException:
      type: object
      properties:
        message:
          type: string
    InvalidInputException:
      type: object
      properties:
        message:
          type: string
    InternalServerException:
      type: object
      properties:
        message:
          type: string
    Build:
      type: object
      properties:
        id:
          type: string
        arn:
          type: string
        buildNumber:
          type: integer
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        currentPhase:
          type: string
        buildStatus:
          type: string
          enum:
          - SUCCEEDED
          - FAILED
          - FAULT
          - TIMED_OUT
          - IN_PROGRESS
          - STOPPED
        projectName:
          type: string
        sourceVersion:
          type: string
externalDocs:
  description: Amazon CodeBuild API Reference
  url: https://docs.aws.amazon.com/codebuild/latest/APIReference/
